Web_App/config/routes.rb
WebApp::Application.routes.draw do
  resources :all_players

  get "pages/home"

  get "pages/contact"

  root :to => 'pages#home'

end

Web_App/app/models/all_player.rb
class AllPlayer < ActiveRecord::Base
end

Web_App/app/controllers/all_players_controller.rb
class AllPlayersController < ApplicationController
  # GET /all_players
  # GET /all_players.json
  def index
    @all_players = AllPlayer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @all_players }
    end
  end

  # GET /all_players/1
  # GET /all_players/1.json
  def show
    @all_player = AllPlayer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @all_player }
    end
  end

  # GET /all_players/new
  # GET /all_players/new.json
  def new
    @all_player = AllPlayer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @all_player }
    end
  end

  # GET /all_players/1/edit
  def edit
    @all_player = AllPlayer.find(params[:id])
  end

  # POST /all_players
  # POST /all_players.json
  def create
    @all_player = AllPlayer.new(params[:all_player])

    respond_to do |format|
      if @all_player.save
        format.html { redirect_to @all_player, notice: 'All player was successfully created.' }
        format.json { render json: @all_player, status: :created, location: @all_player }
      else
        format.html { render action: "new" }
        format.json { render json: @all_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /all_players/1
  # PUT /all_players/1.json
  def update
    @all_player = AllPlayer.find(params[:id])

    respond_to do |format|
      if @all_player.update_attributes(params[:all_player])
        format.html { redirect_to @all_player, notice: 'All player was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @all_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /all_players/1
  # DELETE /all_players/1.json
  def destroy
    @all_player = AllPlayer.find(params[:id])
    @all_player.destroy

    respond_to do |format|
      format.html { redirect_to all_players_url }
      format.json { head :ok }
    end
  end
end

Web_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Web_App/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

end

Web_App/app/helpers/all_players_helper.rb
module AllPlayersHelper
end

Web_App/app/helpers/application_helper.rb
module ApplicationHelper
end

Web_App/app/helpers/pages_helper.rb
module PagesHelper
end

Web_App/app/views/all_players/_form.html.erb
<%= form_for(@all_player) do |f| %>
  <% if @all_player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@all_player.errors.count, "error") %> prohibited this all_player from being saved:</h2>

      <ul>
      <% @all_player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :purse %><br />
    <%= f.number_field :purse %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Web_App/app/views/all_players/edit.html.erb
<h1>Editing all_player</h1>

<%= render 'form' %>

<%= link_to 'Show', @all_player %> |
<%= link_to 'Back', all_players_path %>

Web_App/app/views/all_players/index.html.erb
<h1>Listing all_players</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th>Purse</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @all_players.each do |all_player| %>
  <tr>
    <td><%= all_player.name %></td>
    <td><%= all_player.password %></td>
    <td><%= all_player.purse %></td>
    <td><%= link_to 'Show', all_player %></td>
    <td><%= link_to 'Edit', edit_all_player_path(all_player) %></td>
    <td><%= link_to 'Destroy', all_player, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New All player', new_all_player_path %>

Web_App/app/views/all_players/new.html.erb
<h1>New all_player</h1>

<%= render 'form' %>

<%= link_to 'Back', all_players_path %>

Web_App/app/views/all_players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @all_player.name %>
</p>

<p>
  <b>Password:</b>
  <%= @all_player.password %>
</p>

<p>
  <b>Purse:</b>
  <%= @all_player.purse %>
</p>


<%= link_to 'Edit', edit_all_player_path(@all_player) %> |
<%= link_to 'Back', all_players_path %>

Web_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Web_App/app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

Web_App/app/views/pages/home.html.erb
<div id="left_col" class="red">
  <h4>Username</h4>
  <div class="cash_box">
    <h5>Purse</h5>
    <div class="purse"></div>
    <a href="#" class="ten_piece">10</a>
    <a href="#" class="five_piece">5</a>
    <a href="#" class="one_piece">1</a>      
    <h5>Bet</h5>
    <div class="bet"></div>
  </div>
  
  <div class="stats">      
    <h5>Score</h5>
    <div class="score">0</div>
    <h5>Keepers</h5>
    <div class="keepers"></div>
  </div>
</div>

<div id="outer">
  <button id="roll" class="unavailable">Roll</button>
  <button id="fold">Fold</button>
  <button id="sure_fold">Are you sure you want to fold?</button>
  <button id="rematch">Rematch</button>
  <form>
    </br></br>
    <h4>First Player</h4>
    <div id="p1">
      <input type="checkbox" class="newuser" 
        onClick="if(this.checked == true){ reveal('#p1'); } else { conceal('#p1'); }" />
      <span>New User</span>
    
      <input type="checkbox" class="cpu" 
        onClick="if(this.checked == true){ isCPU('#p1'); } else { isHuman('#p1'); }" />
      <span>Computer</span>
    
      <input type="text" class="uname" value="Username1"
        onfocus="if(this.value == 'Username1') { this.value = ''; }" 
        onblur="if(this.value == '') { this.value = 'Username1'; }"/>
      
      <input type="text" class="pword" value="Password" 
        onfocus="if(this.value == 'Password') { this.value = ''; this.type = 'password' }" 
        onblur="if(this.value == '') { this.value = 'Password'; this.type = 'text' }"/>

      <input type="text" class="pword2" value="Retype Password" 
        onfocus="if(this.value == 'Retype Password') { this.value = ''; this.type = 'password' }" 
        onblur="if(this.value == '') { this.value = 'Retype Password'; this.type = 'text' }"/>
      </br></br>
    </div>
    
    <h4>Second Player</h4>
    <div id="p2">
      <input type="checkbox" class="newuser" 
        onClick="if(this.checked == true){ reveal('#p2'); } else { conceal('#p2'); }" />
      <span>New User</span>
    
      <input type="checkbox" class="cpu" 
        onClick="if(this.checked == true){ isCPU('#p2'); } else { isHuman('#p2'); }" />
      <span>Computer</span>
    
      <input type="text" class="uname" value="Username2"
        onfocus="if(this.value == 'Username2') { this.value = ''; }" 
        onblur="if(this.value == '') { this.value = 'Username2'; }"/>
      
      <input type="text" class="pword" value="Password" 
        onfocus="if(this.value == 'Password') { this.value = ''; this.type = 'password' }" 
        onblur="if(this.value == '') { this.value = 'Password'; this.type = 'text' }" />
    
      <input type="text" class="pword2" value="Retype Password" 
        onfocus="if(this.value == 'Retype Password') { this.value = ''; this.type = 'password' }" 
        onblur="if(this.value == '') { this.value = 'Retype Password'; this.type = 'text' }" />
      </br></br>
    </div>
  </form>
  <div id="inner"></div>
  <h1></h1>
  <h2>It was a TIE!</h2>
  <h5>The the pot will go to the winner of next round</h5>
  <h3>and took home <span></span> in winnings</h3>
  <button id="start">Start</button>
  <button id="end_turn" class="unavailable">End Turn</button>
  <button id="reset_scores" class="half_button">Reset Scores</button>
  <button id="new_players" class="half_button">New Player</button>
</div>

<div id="right_col" class="red">    
  <h4>Username</h4>
  <div class="stats">
    <h5>Score</h5>
    <div class="score">0</div>
    <h5>Keepers</h5>
    <div class="keepers"></div>
  </div>
  
  <div class="cash_box">
    <h5>Purse</h5>
    <div class="purse"></div>      
    <a href="#" class="ten_piece">10</a>
    <a href="#" class="five_piece">5</a>
    <a href="#" class="one_piece">1</a>
    <h5>Bet</h5>
    <div class="bet"></div>
  </div>
</div>